payment/urls.py
from django.urls import path
from .views import invoice_list_view, invoice_detail_view, invoice_payment_method, PaymentMethodRedirect

app_name = 'payment'
urlpatterns = [
    path('invoice/', invoice_list_view, name='invoice_list_view'),
    path('invoice/detail=<int:id>', invoice_detail_view, name='invoice_detail_view'),
    path('method/for=<int:id>', invoice_payment_method, name='invoice_payment_method_view'),
    path('method/for=<int:id>/select=<int:num>/', PaymentMethodRedirect.as_view(), name='invoice_payment_method_redirect')
]

user_regist/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
    path('ticketing/', include('ticketing.urls')),
    path('payment/', include('payment.urls')),
    path('appmanager/', include('appmanager.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
from datetime import date, datetime, timedelta
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Account(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False, default='Unnamed Account')
    type_choice = [
        ('1', 'Bank'),
        ('2', 'another type'),
    ]
    account_type = models.CharField(blank=True, choices= type_choice, max_length=1)
    provider = models.CharField(max_length=100, blank=False, null=False, default='Unnamed Provider')
    number = models.CharField(default='0', max_length=50, blank=False, null=False)
    logo = models.ImageField(upload_to='images/payment/account/', null=True, blank=True)
    role_choice = [
        ('1', 'Company'),
        ('2', 'User'),
    ]
    role = models.CharField(blank=True, choices= role_choice, max_length=1)

class Invoice(models.Model):
    number = models.AutoField(primary_key=True)
    release_date = models.DateTimeField(auto_now=True)
    due_date = models.DateTimeField(auto_now=False, auto_now_add=False, default=timezone.now()+timedelta(days=2))
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    pay_status = models.BooleanField(blank=False, null=False, default=False)
    image_receipt = models.ImageField(upload_to='images/transfer_receipt/', blank=True, null=True)
    price = models.DecimalField(decimal_places=0, max_digits=20, default=0)

    def is_invoice_due(self):
        return timezone.now() >= self.due_date
    
    def get_payment_url(self):
        return reverse('payment:invoice_detail_view', kwargs={'id': self.number})
    
    def get_payment_method_url(self):
        return reverse('payment:invoice_payment_method_view', kwargs={'id': self.number})


class Place(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False, default='Unnamed Account')
    invoice = models.OneToOneField(Invoice, on_delete=models.CASCADE)

ticketing/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date, datetime, timedelta
from filemanager.models import Data
from django.utils import timezone
from payment.models import Invoice
# from .utils import path_and_rename
import os

# Create your models here.
class Location(models.Model):
    name = models.CharField(default="untitled location", blank=False, null=False, max_length=120)
    street = models.CharField(default="untitled street", blank=False, null=False, max_length=300)
    sub_district = models.CharField(default="untitled sub district", blank=False, null=False, max_length=120)
    city = models.CharField(default="untitled city", blank=False, null=False, max_length=120)
    province_or_state = models.CharField(default="untitled province", blank=False, null=False, max_length=120)
    country = models.CharField(default="untitled country", blank=False, null=False, max_length=120)
    postal_code = models.DecimalField(decimal_places=0, max_digits=5)
    google_maps = models.URLField(blank=True, null=True)

    def __str__(self):
        return '%s, %s' %(self.city, self.province_or_state)

class Event(models.Model):
    name = models.CharField(default="untitled event", blank=False, null=False, max_length=120)
    date = models.DateField(auto_now=False, auto_now_add=False)
    time = models.TimeField(auto_now_add=False, auto_now=False)
    due_registration = models.DateField(auto_now=False, auto_now_add=False, default=datetime.now()-timedelta(days=3))
    topic = models.CharField(default="untitled topic", blank=False, null=False, max_length=120)
    event_type_choice = [
        ('SM', 'Seminar'),
        ('HO', 'Hand On'),
        ('PL', 'Pelatihan'),
        ('WS', 'Workshop'),
        ('SW', 'Seminar dan workshop')
    ]
    event_type = models.CharField(blank=True, choices= event_type_choice, max_length=2)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    participant = models.ManyToManyField(User, through='EventParticipant', related_name='participants')
    price = models.DecimalField(decimal_places=0, max_digits=10, default=0)
    price_plan = models.ManyToManyField('PricePlan', related_name='event_price_plan')
    data = models.ManyToManyField(Data, through="DataEvent", related_name="data_event")
    document = models.ManyToManyField('Document', related_name='event_document')
    poster = models.ImageField(upload_to='static/event_poster/', blank=True, null=True)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ticketing:event_detail_view', kwargs={'id': self.id})

    def get_register_url(self):
        return reverse('ticketing:event_register_view', kwargs={'id': self.id})
    
    def get_payment_url(self):
        return reverse('ticketing:payment_detail_view', kwargs={'id': self.id})
    
    def get_ticket_url(self):
        return reverse('ticketing:generate_pdf', kwargs={'id': self.id})

    
    @property
    def is_past_due(self):
        return date.today() >= self.date

    def is_registration_due(self):
        return date.today() >= self.due_registration

class EventParticipant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    roles = [
        ('1', 'Peserta'),
        ('2', 'Narasumber')
    ]
    role = models.CharField(blank=False, max_length=1, choices=roles, default='1')
    # payment = models.OneToOneField('EventPayment', on_delete=models.CASCADE, null=True)
    invoice = models.OneToOneField(Invoice, on_delete=models.CASCADE, null=True, blank=True)
    barcode = models.URLField(blank=True, null=True, editable=False)
    # barcode_image = models.ImageField(upload_to='media/barcode')

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)
    
    def get_payment_method_url(self):
        if self.invoice:
            return reverse('payment:invoice_payment_method_view', kwargs={'id': self.invoice.number})
        return 

class DataEvent(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    data = models.ForeignKey(Data, on_delete=models.CASCADE)

    def __str__(self):
        return self.data.file.name

class EventPayment(models.Model):
    due_date = models.DateTimeField(auto_now=False, auto_now_add=False, default=timezone.now()+timedelta(days=2))
    pay_status = models.BooleanField(blank=False, null=False, default=False)
    image_receipt = models.ImageField(upload_to='images/transfer_receipt/', blank=True, null=True)

class Document(models.Model):
    name = models.CharField(default="untitled document", blank=False, null=False, max_length=150)
    value = models.DecimalField(decimal_places=0, default=0, max_digits=3)
    date_of_release = models.DateField(null=True, blank=True)
    file = models.FileField(upload_to='media/document/pdf/', blank=True, null=True)

    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return '%s(%s)' %(self.name, self.id)

class PricePlan(models.Model):
    price = models.DecimalField(decimal_places=0, max_digits=20, default=0)
    role_choices = [
        ('PR', 'perawat'),
        ('DR', 'dokter'),
        ('BD', 'bidan'),
        ('OT', 'other')
    ]
    role= models.CharField(blank=True, choices= role_choices, max_length=2)

    def __str__(self):
        return '%s(%s)' %(self.price, self.get_role_display())

payment/views.py
from django.shortcuts import render
from .models import Invoice, Account
from ticketing.models import PricePlan
from django.contrib.auth.decorators import login_required
from .form import UpdateTranferReceipt
from django.views.generic import RedirectView
from django.http import Http404, HttpResponse, HttpResponseRedirect

# Create your views here.
@login_required
def invoice_list_view(request):
    invoice_list = Invoice.objects.filter(eventparticipant__user = request.user)
    context = {
        'invoice_list' : invoice_list
    }

    return render(request, 'invoice_list_view.html', context)

def invoice_payment_method(request, id):
    invoice = Invoice.objects.get(number=id)
    payment_method = Account.objects.filter(role = '1')
    context = {
        'payment_method' : payment_method,
        'invoice' :invoice
    }
    return render(request, 'payment_method.html', context)

class PaymentMethodRedirect(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        number = self.kwargs.get('id')
        num = self.kwargs.get('num')
        print(number)
        invoice = Invoice.objects.get(number=number)
        payment_method = Account.objects.get(id=num)
        print(payment_method)
        invoice.account = payment_method
        invoice.save()
        return invoice.get_payment_method_url()


def invoice_detail_view(request, id):
    invoice = Invoice.objects.filter(eventparticipant__user = request.user, number = id)
    event = invoice[0].eventparticipant.event

    if invoice[0].account != None:
        if not invoice[0].is_invoice_due():
            if request.method == 'POST':
                form = UpdateTranferReceipt(request.POST, request.FILES, instance=invoice[0])
                if form.is_valid:
                    update = form.save(commit = False)
                    update.save()
            else:
                form = UpdateTranferReceipt(instance=invoice[0])
            context = {
                'form' : form,
                'invoice' : invoice,
            }

            return render(request, 'invoice_detail_view.html', context)
        else :
            raise Http404("Invoice not Found")
    else:
        return HttpResponseRedirect(invoice[0].eventparticipant.get_payment_method_url())

payment/templates/invoice_detail_view.html
{% extends 'dashboard.html' %}
{% load i18n %}
{% load humanize %}
{% block content %}
{% language 'id' %}
<div class="container-fluid">
    <div class="card">
        <div class="card-body"> 
            <h5 class="text-danger text-center font-weight-bold mb-4">Segera Selesaikan Pembayaran Anda</h5>
            <div class="card border-secondary timer-panel mx-auto mb-4">
                <div class="card-body">
                    <h6 class="text-center font-weight-bold">Sisa Waktu Pembayaran Anda</h6>
                    <h4 class="text-center"> 
                        <div class="timer" id="days"></div>
                        <div class="timer" id="hours"></div>
                        <div class="timer" id="minutes"></div>
                        <div class="timer" id="seconds"></div>
                        <div class="timer" id="finish"></div>
                    </h4>
                </div>
            </div>
            <div class="alert alert-warning timer-panel mx-auto" role="alert">
                <h6 class="text-center">
                    Bayar sebelum {{invoice.0.due_date|date:"l, d M Y"}} pukul {{invoice.0.due_date|date:"H:m:i "}}
                </h6>
            </div>
            <h5 class="text-grey-500 text-center font-weight-bold mb-4">Detail Transaksi</h5>
            <ul class="list-group list-group-flush timer-panel mx-auto mb-4">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-6 col-lg-4">Name :</div>
                        <div class="col-lg-8">{{invoice.0.eventparticipant.event.name}}</div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-6 col-lg-4">Jenis :</div>
                        <div class="col-lg-8">{{invoice.0.eventparticipant.event.get_event_type_display}}</div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-6 col-lg-4">Harga :</div>
                        <div class="col-lg-8">Rp. {{invoice.0.price|intcomma}}</div>
                        
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-6 col-lg-4">Status :</div>
                        {% if invoice.0.pay_status and invoice.0.image_receipt.url %}
                            <div class="col-lg-8 font-weight-bold text-success">Lunas</div>
                        {% elif invoice.0.pay_status == False and not invoice.0.image_receipt %}
                            <div class="col-lg-8 font-weight-bold text-danger">Belum Terbayar</div>
                        {% elif invoice.0.pay_status == False and invoice.0.image_receipt %}
                            <div class="col-lg-8 font-weight-bold text-warning">Menunggu Konfirmasi</div>
                        {% endif %}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-6 col-lg-4">Metode :</div>
                        {% if invoice.0.account.role == '1' %}
                            <div class="col-lg-8">Transfer Bank</div>
                        {% endif %}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        {% if invoice.0.account.role == '1' %}
                            <div class="col-6 col-lg-4">Rekening :</div>
                            <div class="col-lg-8">{{invoice.0.account.number}} a/n {{invoice.0.account.name}}</div>
                        {% endif %}
                    </div>
                </li>
              </ul>
            
            {% if invoice.0.pay_status == False %}         
            <div class="text-center">
                <button type="button" class="btn btn-primary btn-icon-split" data-toggle="modal" data-target=".bd-example-modal-lg">
                    <span class="icon text-white-50"><i class="fas fa-receipt"></i></span>
                    <span class="text">Unggah Bukti Pembayaran</span>
                </button>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- modal upload -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger font-weight-bold">Upload Bukti Pembayaran</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-secondary bg-gray-100 mt-2" role="alert">
                    <i class="fas fa-lightbulb text-warning"></i>
                    Unggah bukti pembayaran dapat mempercepat verifikasi pembayaran
                </div>
                <p>Pastikan bukti pembayaran menampilkan:</p>
                <div class="row">
                    <div class="col-lg-6">
                        <ul>
                            <li class="font-weight-bold">Tanggal/Waktu Transfer</li>
                            <li class="list-unstyled">contoh: tgl. 04/06/19 / jam 07:24:06</li>
                            <li class="font-weight-bold">Status Berhasil</li>
                            <li class="list-unstyled">contoh: Transfer BERHASIL, Transaksi Sukses</li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul>
                            <li class="font-weight-bold">Detail Penerima</li>
                            <li class="list-unstyled">contoh: Transfer ke Rekening PT ASM</li>
                            <li class="font-weight-bold">Jumlah Transfer</li>
                            <li class="list-unstyled">contoh: Rp 123.456,00</li>
                        </ul>
                    </div>
                </div>                
                {% if invoice.0.image_receipt %}    
                <button id="delete_receipt" class="btn btn-danger">Ganti</button>
                <img id="image_receipt_uploaded" src="{{invoice.0.image_receipt.url}}" alt="your image" class="img-fluid img-thumbnail"/>
                {% else %}
                <form action="" method="POST" class="mb-2" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="d-flex justify-content-between">
                        {{form.image_receipt}}
                        <input type="submit" id="upload_btn" value="Upload" class="collapse btn btn-primary">
                    </div>
                </form>
                <img id="image_receipt_preview" src="#" alt="your image" class="collapse img-fluid img-thumbnail"/>
                {% endif %}

                <!-- form edit receipt -->
                <form action="" method="POST" class="mb-2 collapse" enctype='multipart/form-data' id='edit-receipt'>
                    {% csrf_token %}
                    <div class="d-flex justify-content-between">
                        {{form.image_receipt}}
                        <button type="button" id="undelete_receipt" class="collapse btn btn-info mr-2">Batal</button>
                        <input type="submit" id="upload_btn" value="Upload" class="collapse btn btn-primary">
                    </div>
                </form>
                <img id="image_receipt_preview" src="#" alt="your image" class="collapse img-fluid img-thumbnail"/>
            </div>
        </div>
    </div>
</div>
<style>
@media only screen and (min-width: 500px) {
    .timer-panel{
        width: 540px;
    }
}


.timer {
  display: inline-block;
}
    .counter-name {
  display: block;
}
</style>
{% endlanguage %}
{% endblock content %}
    

{% block jquery %}
<script>
function makeTimer() {

//		var endTime = new Date("29 April 2018 9:56:00 GMT+01:00");	
        var endTime = new Date('{{invoice.0.due_date|date:"d M Y H:m:i "}}');			
            endTime = (endTime/ 1000);

        var now = new Date();
        now = (Date.parse(now) / 1000);

        if(now<=endTime){
            var timeLeft = endTime - now;
        }else{
            var timeLeft = -1;
        }

        var days = Math.floor(timeLeft / 86400); 
        var hours = Math.floor((timeLeft - (days * 86400)) / 3600);
        var minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600 )) / 60);
        var seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));
        
        if (hours < "10") { hours = "0" + hours; }
        if (minutes < "10") { minutes = "0" + minutes; }
        if (seconds < "10") { seconds = "0" + seconds; }

        if(timeLeft >= 0){
            $("#days").html(days + " :" + "<span class='counter-name h5'> Hari</span>");
            $("#hours").html(hours + " :" + "<span class='counter-name h5'> Jam</span>");
            $("#minutes").html(minutes + " :" + "<span class='counter-name h5'> Menit</span>");
            $("#seconds").html(seconds + "<span class='counter-name h5'> Detik</span>");
        }else if(timeLeft < 0){
            $("#days").html();
            $("#hours").html();
            $("#minutes").html();
            $("#seconds").html();
            $("#finish").html("<span>Finish</span>");
        }		

}

setInterval(function() { makeTimer(); }, 1000);

function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    
    reader.onload = function(e) {
        // if($('#undelete_receipt').length){
        //     $('#undelete_receipt').collapse('hide');
        // }
      $('#image_receipt_preview').attr('src', e.target.result);
      $('#image_receipt_preview').collapse('show');
      $('#upload_btn').collapse('show');
    }
    
    reader.readAsDataURL(input.files[0]);
  }else{
    $('#image_receipt_preview').collapse('hide');
    $('#upload_btn').collapse('hide');
    }
}

$("#image_receipt").change(function() {
  readURL(this);
});

$('#delete_receipt').on('click', function(){
    $(this).hide();
    $('#image_receipt_uploaded').hide();
    $('#edit-receipt').collapse('show');
    $('#undelete_receipt').collapse('show');
});

$('#undelete_receipt').on('click', function(){
    $(this).collapse('hide');
    $('#delete_receipt').show();
    $('#image_receipt_uploaded').show();
    $('#edit-receipt').collapse('hide');
});

$(document).ready(function(){
    $('#invoice').addClass('active');
    $('#invoice_mobile').addClass('active');
    $('#my_invoice').addClass('active');
});
    
</script>
    
{% endblock jquery %}
    

payment/templates/invoice_list_view.html
{% extends 'dashboard.html' %}
{% load i18n %}
{% load humanize %}


{% block content %}
{% language 'id' %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-center mb-2">
        <h5 class="h3 mb-0 text-gray-800 mb-2 font-weight-bold">
            Daftar Tagihan Anda
        </h5>
    </div>
    {% for instance in invoice_list %}
        {% if instance.is_invoice_due == False %} 
        <div class="card sunatlem-panel mx-auto mb-4 shadow">
            <div class="card-body">
                <div class="d-flex bd-highlight">
                    <div class="p-2 flex-grow-1 bd-highlight">
                        <div class="row">
                            <div class="col-lg-6">
                                <h5 class="font-weight-bold mb-0">{{instance.eventparticipant.event.name}} </h5>
                                <p class="mb-1">#{{instance.number}}</p>
                                {% if instance.account.role == '1' %}
                                    <p class="font-weight-bold mb-0">Transfer Bank</p>
                                    <p class="mb-0">{{instance.account.provider}}</p>
                                    <p class="mb-0">ke {{instance.account.number}}</p>
                                    <p class="mb-1">a/n {{instance.account.name}}</p>
                                    {{instance.eventparticipant.event.price_plan.all.0.get_role_display.lower}}
                                {% endif %}      
                            </div>
                            <div class="col-lg-6">
                                <p class="font-weight-bold mb-0">Bayar Sebelum</p>
                                <p class="font-weight-light mb-0">{{instance.due_date|date:'d F Y'}} Pukul {{instance.due_date|date:'H:i'}}</p>                
                                {% if instance.pay_status and instance.image_receipt %}
                                    <p class="font-weight-bold text-success">Lunas</p>
                                {% elif instance.pay_status == False and instance.image_receipt %}
                                    <p class="font-weight-bold text-warning">Menunggu Konfirmasi</p>
                                {% elif instance.pay_status == False and not instance.image_receipt  %}
                                    <p class="font-weight-bold text-danger">Belum Terbayar</p>
                                {% endif %}
                                    
                            </div>
                        </div>

                    </div>
                    <div class="p-2 bd-highlight border-left">
                        <p class="mb-0">Total</p>
                        <p class="text-danger">Rp. {{instance.price|intcomma}}</p>
                    </div>
                </div>
                <div class="d-flex justify-content-end mt-2 mb-2">
                    <a href="{{instance.get_payment_url}}" type="button" class="btn btn-sm btn-info font-weight-bold">
                        Lihat Detail Pembayaran
                    </a>
                </div>
                
                {% if not instance.pay_status and not instance.image_receipt %}    
                <div class="d-flex justify-content-end mt-2 mb-2">
                    <a href="{{instance.get_payment_method_url}}" type="button" class="btn btn-sm btn-info font-weight-bold">
                       Ubah Cara Pembayaran
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>
{% endlanguage %}
{% endblock content %}
    

{% block jquery %}
<script>
$(document).ready(function(){
    $('#invoice').addClass('active');
    $('#invoice_mobile').addClass('active');
    $('#my_invoice').addClass('active');
})
</script>
    
{% endblock jquery %}
    
    

payment/templates/payment_method.html
{% extends 'dashboard.html' %}

{% block content %}

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Pilih Metode Pembayaran</h6>
        </div>
        <div class="card-body">
            <div>
                <h5>
                    Nomor Invoice : #{{invoice.number}}
                </h5>
            </div>
            <div class="list-group"> 
                {% if invoice.account != null %}                    
                <a href="#" class="list-group-item list-group-item-action active">
                    <div class="d-flex justify-content-between">
                        <div>
                            <h6 class="font-weight-bold">Metode Saat ini</h6>
                            <h6 class="payment-item">   
                                {% if invoice.account.get_account_type_display == 'Bank' %}
                                Bank Transfer   
                                {% endif %}
                            </h6>
                            <h6 class="payment-item">{{invoice.account.provider}}</h6>
                            <!-- <h6 class="payment-item">{{instance.number}} a/n {{instance.name}}</h6> -->
                        </div>
                        <div class="my-auto">
                            <img src="{{invoice.account.logo.url}}" alt="" class="img-fluid payment-method-img">
                        </div>
                    </div>
                </a>
                {% endif %}

                {% for instance in payment_method %}
                <a href="{% url 'payment:invoice_payment_method_redirect' invoice.number instance.id %}" class="list-group-item list-group-item-action">
                    <div class="d-flex justify-content-between">
                        <div>
                            <h6 class="payment-method font-weight-bold">   
                                {% if instance.get_account_type_display == 'Bank' %}
                                Bank Transfer   
                                {% endif %}
                            </h6>
                            <h6 class="payment-item">{{instance.provider}}</h6>
                            <!-- <h6 class="payment-item">{{instance.number}} a/n {{instance.name}}</h6> -->
                        </div>
                        <div class="my-auto">
                            <img src="{{instance.logo.url}}" alt="" class="img-fluid payment-method-img">
                        </div>
                    </div>
                </a>
                {% endfor %}        
            </div>    
            {% if invoice.account != null %}
            <div class="d-flex justify-content-end mt-4">
                <a href="{{invoice.get_payment_url}}" type="button" class="btn btn-sm btn-primary">Bayar Sekarang</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
    
{% endblock content %}


{% block jquery %}
    <script>
        $(document).ready(function(){
            $('#invoice').addClass('active');
            $('#invoice_mobile').addClass('active');
            $('#my_invoice').addClass('active');
        });
    </script>
{% endblock jquery %}
    
    