payment/urls.py
from django.urls import path
from .views import invoice_list_view, invoice_detail_view, invoice_payment_method, PaymentMethodRedirect

app_name = 'payment'
urlpatterns = [
    path('invoice/', invoice_list_view, name='invoice_list_view'),
    path('invoice/detail=<int:id>', invoice_detail_view, name='invoice_detail_view'),
    path('method/for=<int:id>', invoice_payment_method, name='invoice_payment_method_view'),
    path('method/for=<int:id>/select=<int:num>/', PaymentMethodRedirect.as_view(), name='invoice_payment_method_redirect')
]

registration/urls.py
from django.urls import path
from .views import home_view, signup_view, signin_view, user_logout, edit_user_view, edit_password_view, edit_profile_view, profile_view, create_profile

app_name = 'registration'
urlpatterns = [
    path('', home_view, name='home'),
    path('sign_up/', signup_view, name='sign_up'),
    path('sign_in/', signin_view, name='sign_in'),
    path('logout/', user_logout, name='user_logout'),
    path('edit/', edit_user_view, name='edit_user'),
    path('change_password/', edit_password_view, name='edit_password'),
    path('edit_profile/', edit_profile_view, name='edit_profile'),
    path('profile/', profile_view, name='profile'),
    path('create_profile/', create_profile, name='create_profile')
]

ticketing/urls.py
from django.urls import path
from .views import (
    event_list_view, 
    event_detail_view, 
    event_registered_view, 
    event_register_view, 
    my_event_view, 
    payment_detail_view,
    GeneratePDF
)

app_name = 'ticketing'

urlpatterns = [
    path('daftar_event/', event_list_view, name='event_list_view'),
    path('daftar_event/<int:id>/', event_detail_view, name='event_detail_view'),
    path('registered/', event_registered_view, name='event_registered_view'),
    path('register/<int:id>/', event_register_view, name='event_register_view'),
    path('my_event/', my_event_view, name='my_event_view'),
    path('payment/<int:id>/', payment_detail_view, name='payment_detail_view'),
    path('pdf/ticket=<int:id>/', GeneratePDF.as_view(), name='generate_pdf')
]

user_regist/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
    path('ticketing/', include('ticketing.urls')),
    path('payment/', include('payment.urls')),
    path('appmanager/', include('appmanager.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     <!--Import Google Icon Font-->
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     
     <!--Let browser know website is optimized for mobile-->
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- Static Files -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
    <link rel="stylesheet" href="{% static 'css/sunatlem.css' %}">

     <!--Import materialize.css-->
     <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
     <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>


    <title>{% block page_title %} {% endblock page_title %} </title>
</head>

<body>
    {% block content %}{% endblock content %}

    {% include 'footer.html' %}
    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    
    
    {% block jquery %}
        
    {% endblock jquery %}
        
</body>
</html>

templates/home.html
{% extends 'non-dashboard-base.html' %}
{% load static %}

{% block title %}
  SunatLem App
{% endblock title %}
  
{% block content %}
  <div class="jumbotron jumbotron-fluid home-cover">
    <div class="container">
      <div class="row">
        <div class="col-lg">
          <img src="{% static 'img/sunatlem.png' %}" alt="" class="img-fluid js-tilt" data-tilt="" style="transform: perspective(300px) rotateX(0deg) rotateY(0deg); will-change: transform;">
        </div>
        <div class="col-lg">
          <h1 class="display-4 sunatlem-brand">SunatLem <span>App</span></h1>
          <p class="h5 mb-4 mt-2">Selamat Datang di Aplikasi SunatLem. <br> Satu Aplikasi untuk berbagai keperluan.</p>
          <a href="{% url 'registration:sign_in' %}" type="button" class="btn btn-primary button">Login</a>
          <a href="{% url 'registration:sign_up' %}" type="button" class="btn btn-success button">Daftar</a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container">
  <!-- panel section -->
    <div class="d-flex justify-content-center">
      <div class="bg-white row panel">
        <div class="col-lg panel-item">
          <img src="{% static 'img/learn.png' %}" alt="" class="img-fluid js-tilt float-left" data-tilt="" style="transform: perspective(300px) rotateX(0deg) rotateY(0deg); will-change: transform;">
          <h5 class="text-panel">Kelas Pelatihan</h5>
        </div>
        <div class="col-lg d-flex justify-content-center">
          <img src="{% static 'img/shop.png' %}" alt="" class="img-fluid js-tilt float-left" data-tilt="" style="transform: perspective(300px) rotateX(0deg) rotateY(0deg); will-change: transform;">
          <h5 class="text-panel">SunatLem Shop</h5>
        </div>
        <div class="col-lg d-flex justify-content-center">
          <img src="{% static 'img/service.png' %}" alt="" class="img-fluid js-tilt float-left" data-tilt="" style="transform: perspective(300px) rotateX(0deg) rotateY(0deg); will-change: transform;">
          <h5 class="text-panel">Layanan Pasien</h5>
        </div>
      </div>
    </div>
    
  <!-- content section -->
  </div>
{% endblock content %}
    

templates/js_core.html
{% load static %}
  
<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script
  src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"
  integrity="sha256-xNjb53/rY+WmG+4L6tTl9m6PpqknWZvRt0rO1SRnJzw="
  crossorigin="anonymous"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>

<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

<!-- Popper Javascript -->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>

<!-- select2 javascript -->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>

<!-- tilt javascript -->
<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>

<!-- main javascript -->
<script src="{% static 'js/main.js' %}"></script>

<script >
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>

templates/navbar.html
<nav class="red darken-1">
    <div class="container">
        <div class="nav-wrapper">
        <a href="#!" class="brand-logo sunatlem-brand">SunatLem Event</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">Javascript</a></li>
            <li><a href="mobile.html">Mobile</a></li>
        </ul>
    </div>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo">
<li><a href="sass.html">Sass</a></li>
<li><a href="badges.html">Components</a></li>
<li><a href="collapsible.html">Javascript</a></li>
<li><a href="mobile.html">Mobile</a></li>
</ul>

  
  {% block jquery %}
  <script>
    $(document).ready(function(){
        $('.sidenav').sidenav();
    });
  </script> 
  {% endblock jquery %}
      

templates/non-dashboard-base.html
<head>
{% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  
    <title>
        {% block title %}
            
        {% endblock title %}        
    </title>
  
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet"> -->

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sunatlem.css' %}">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    

    <link rel="icon" href="{% static 'img/sunatlem_icon.ico' %}" type="image/gif" sizes="64x64">
    
  </head>
  
  <body class="bg-gray-100">
      
      {% block content %}
          
      {% endblock content %}

      {% include 'js_core.html' %}
  </body>
  
  </html>
  
  
  {% block jquery %}

  {% endblock jquery %}
  
  

templates/sidebar-dashboard.html
<ul class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion sunatlem-toggled" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <!-- <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div> -->
      <div class="sunatlem-brand mx-3">
        <h6 class="h5 dash">SunatLem App</h6>
      </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item" id='home'>
      <a class="nav-link" href="{% url 'registration:home' %}">
          <i class="fas fa-home"></i>
        <span>Dashboard</span>
      </a>   
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Interface
    </div>

    <!-- Nav Item - Event Collapse Menu -->
    <li class="nav-item" id=event>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEvent" aria-expanded="true" aria-controls="collapseTwo">
            <i class="far fa-calendar-alt"></i>
            <span>Event</span>
        </a>
        <div id="collapseEvent" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" id="my_event" href="{% url 'ticketing:my_event_view' %}">Event Saya</a>
              <a class="collapse-item" id="register_event" href="{% url 'ticketing:event_list_view' %}">Pendaftaran Event</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Materi -->
    <!-- <li class="nav-item">
        <a class="nav-link" href="index.html">
            <i class="far fa-file-alt"></i>
        <span>Materi</span></a>
    </li> -->

    <!-- Nav Item - Tagihan -->
    <li class="nav-item" id="invoice">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInvoice" aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-file-invoice"></i>
        <span>Pembayaran</span>
      </a>
      <div id="collapseInvoice" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <a class="collapse-item" id="my_invoice" href="{% url 'payment:invoice_list_view' %}">Tagihan</a>
        </div>
      </div>

    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>